services:
  - type: web
    name: cartify-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
